version: '3'
services:
  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - APP_NAME=app1
  
  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - APP_NAME=app2
    
  app3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - APP_NAME=app3