version: '3'
services:
  app1:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=app1
  
  app2:
    build: .
    ports:
      - "5001:5000"
    environment:
      - APP_NAME=app2
    
  app3:
    build: .
    ports:
      - "5002:5000"
    environment:
      - APP_NAME=app3